CREATE TABLE IF NOT EXISTS account (
  id BIGSERIAL PRIMARY KEY,
  type INTEGER NOT NULL DEFAULT 0,
  name TEXT NOT NULL DEFAULT '',
  currency TEXT NOT NULL DEFAULT 'IDR',
  ordering INTEGER NOT NULL DEFAULT 0,
  currency_symbol TEXT NOT NULL DEFAULT 'Rp',
  balance INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS wallet (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  color TEXT NOT NULL DEFAULT '#2563eb',
  amount INTEGER NOT NULL DEFAULT 0,
  initial_amount INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  account_id BIGINT NOT NULL DEFAULT 1,
  ordering INTEGER NOT NULL DEFAULT 0,
  exclude INTEGER NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'IDR',
  icon INTEGER NOT NULL DEFAULT 0,
  type INTEGER NOT NULL DEFAULT 0,
  due_date BIGINT NOT NULL DEFAULT 0,
  statement_date BIGINT NOT NULL DEFAULT 0,
  credit_limit INTEGER NOT NULL DEFAULT 0,
  hidden INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS category (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  color TEXT NOT NULL DEFAULT '#78716c',
  type INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  ordering INTEGER NOT NULL DEFAULT 0,
  icon INTEGER NOT NULL DEFAULT 0,
  account_id BIGINT NOT NULL DEFAULT 1,
  default_category INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS subcategory (
  id BIGSERIAL PRIMARY KEY,
  category_id BIGINT NOT NULL DEFAULT 0,
  name TEXT NOT NULL DEFAULT '',
  ordering INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS trans (
  id BIGSERIAL PRIMARY KEY,
  note TEXT NOT NULL DEFAULT '',
  memo TEXT NOT NULL DEFAULT '',
  type INTEGER NOT NULL DEFAULT 0,
  amount INTEGER NOT NULL DEFAULT 0,
  date_time BIGINT NOT NULL DEFAULT 0,
  account_id BIGINT NOT NULL DEFAULT 1,
  fee_id BIGINT NOT NULL DEFAULT 0,
  category_id BIGINT NOT NULL DEFAULT 0,
  subcategory_id BIGINT NOT NULL DEFAULT 0,
  wallet_id BIGINT NOT NULL DEFAULT 0,
  transfer_wallet_id BIGINT NOT NULL DEFAULT -1,
  trans_amount INTEGER NOT NULL DEFAULT 0,
  debt_id BIGINT NOT NULL DEFAULT 0,
  debt_trans_id BIGINT NOT NULL DEFAULT 0,
  budget_id BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS media (
  id BIGSERIAL PRIMARY KEY,
  path TEXT NOT NULL DEFAULT '',
  trans_id BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS budget (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  amount INTEGER NOT NULL DEFAULT 0,
  spent INTEGER NOT NULL DEFAULT 0,
  status INTEGER NOT NULL DEFAULT 0,
  period INTEGER NOT NULL DEFAULT 0,
  color TEXT NOT NULL DEFAULT '#78716c',
  repeat INTEGER NOT NULL DEFAULT 0,
  account_id BIGINT NOT NULL DEFAULT 1,
  category_id BIGINT NOT NULL DEFAULT 0,
  start_date BIGINT DEFAULT NULL,
  end_date BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS budgetCategory (
  id BIGSERIAL PRIMARY KEY,
  budget_id BIGINT NOT NULL DEFAULT 0,
  category_id BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_budget (
  id BIGSERIAL PRIMARY KEY,
  category_id BIGINT NOT NULL DEFAULT 0,
  amount INTEGER NOT NULL DEFAULT 0,
  note TEXT NOT NULL DEFAULT '',
  target_date BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS debt (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  lender TEXT NOT NULL DEFAULT '',
  color TEXT NOT NULL DEFAULT '#78716c',
  pay INTEGER NOT NULL DEFAULT 0,
  amount INTEGER NOT NULL DEFAULT 0,
  due_date BIGINT NOT NULL DEFAULT 0,
  lend_date BIGINT NOT NULL DEFAULT 0,
  account_id BIGINT NOT NULL DEFAULT 1,
  status INTEGER NOT NULL DEFAULT 0,
  type INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS debtTrans (
  id BIGSERIAL PRIMARY KEY,
  amount INTEGER NOT NULL DEFAULT 0,
  date_time BIGINT NOT NULL DEFAULT 0,
  debt_id BIGINT NOT NULL DEFAULT 0,
  note TEXT NOT NULL DEFAULT '',
  type INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS goal (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  color TEXT NOT NULL DEFAULT '#2563eb',
  saved INTEGER NOT NULL DEFAULT 0,
  amount INTEGER NOT NULL DEFAULT 0,
  status INTEGER NOT NULL DEFAULT 0,
  account_id BIGINT NOT NULL DEFAULT 1,
  expect_date BIGINT NOT NULL DEFAULT 0,
  achieve_date BIGINT NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'IDR'
);

CREATE TABLE IF NOT EXISTS goalTrans (
  id BIGSERIAL PRIMARY KEY,
  amount INTEGER NOT NULL DEFAULT 0,
  date_time BIGINT NOT NULL DEFAULT 0,
  goal_id BIGINT NOT NULL DEFAULT 0,
  type INTEGER NOT NULL DEFAULT 0,
  note TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS recurring (
  id BIGSERIAL PRIMARY KEY,
  note TEXT NOT NULL DEFAULT '',
  memo TEXT NOT NULL DEFAULT '',
  type INTEGER NOT NULL DEFAULT 0,
  recurring_type INTEGER NOT NULL DEFAULT 0,
  repeat_type INTEGER NOT NULL DEFAULT 0,
  repeat_date TEXT NOT NULL DEFAULT '',
  increment INTEGER NOT NULL DEFAULT 0,
  amount INTEGER NOT NULL DEFAULT 0,
  date_time BIGINT NOT NULL DEFAULT 0,
  until_time BIGINT NOT NULL DEFAULT 0,
  last_update_time BIGINT NOT NULL DEFAULT 0,
  account_id BIGINT NOT NULL DEFAULT 1,
  category_id BIGINT NOT NULL DEFAULT 0,
  wallet_id BIGINT NOT NULL DEFAULT 0,
  subcategory_id BIGINT NOT NULL DEFAULT 0,
  transfer_wallet_id BIGINT NOT NULL DEFAULT 0,
  trans_amount INTEGER NOT NULL DEFAULT 0,
  is_future INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS template (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  note TEXT NOT NULL DEFAULT '',
  memo TEXT NOT NULL DEFAULT '',
  amount INTEGER NOT NULL DEFAULT 0,
  category_id BIGINT NOT NULL DEFAULT 0,
  subcategory_id BIGINT NOT NULL DEFAULT 0,
  wallet_id BIGINT NOT NULL DEFAULT 0,
  account_id BIGINT NOT NULL DEFAULT 1,
  ordering INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS currency (
  id BIGSERIAL PRIMARY KEY,
  code TEXT NOT NULL DEFAULT '',
  rate DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  account_id BIGINT NOT NULL DEFAULT 1
);

CREATE OR REPLACE FUNCTION update_wallet_balance(wallet_id BIGINT, delta INTEGER)
RETURNS void AS $$
BEGIN
  UPDATE wallet SET amount = amount + delta WHERE id = wallet_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
